# nonk8s
apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-qinyongxue
  annotations:
    # Add supports for Halo App Store
    # https://halo.run/store/apps/app-vGuQB
    "store.halo.run/app-id": "app-vGuQB11"
spec:
  displayName: Qinyongxue
  author:
    name: JiangChangXiong
    website: https://youdiandongxi.cn
  description: 勤勇学主题
  logo: https://youdiandongxi.cn/upload/logo.png
  website: https://github.com/jiangchangxiong/halo-theme-qinyongxue
  repo: https://github.com/jiangchangxiong/halo-theme-qinyongxue.git
  settingName: "halo-theme-qinyongxue-setting"
  configMapName: "halo-theme-qinyongxue-configMap"
  version: 1.0.1
  require: ">=2.0.0"
